#!/bin/bash

cat basicmod/BASICROM.BIN > MULTIROM.BIN        # regular BASIC NL v1.1    (00)
cat roms/basic_nl_v1_1_a2.bin >> MULTIROM.BIN   # regular BASIC NL v1.1a2  (01)
cat roms/basic_en_v1_0.bin >> MULTIROM.BIN      # regular BASIC EN v1.1a2  (02)
cat roms/JWSBasic.bin >> MULTIROM.BIN           # JWS Basic                (03)
cat BASICBOOTSTRAP.BIN >> MULTIROM.BIN          # SD-CARD BASIC            (04)
cat FLASHER.BIN >> MULTIROM.BIN                 # flasher utility          (05)
cat RAMTEST.BIN >> MULTIROM.BIN                 # ram test                 (06)
cat roms/maintenance_v2.bin >> MULTIROM.BIN     # maintenance utility      (07)
cat roms/bildschirmtext.bin >> MULTIROM.BIN     # bildschirmtext           (08)
cat roms/Forth.bin >> MULTIROM.BIN              # Forth programming lang   (09)
cat roms/assembler_v5_9.bin >> MULTIROM.BIN     # Assembler 5.9            (0A)
cat roms/zemon_v1_4.bin >> MULTIROM.BIN         # Zemon v1.4               (0B)
cat roms/flexbase_v1_6.bin >> MULTIROM.BIN      # Flexbase v1.6            (0C) 
cat roms/familiegeheugen_v4.bin                 # Familiegeheugen v4       (0D)
cat roms/tekst_v1.bin >> MULTIROM.BIN           # Tekst v1                 (0E)
cat roms/text2000_v3.bin >> MULTIROM.BIN        # Text2000 v3              (0F)
cat roms/text2_de.bin >> MULTIROM.BIN           # Text2 DE v2              (10)
cat roms/wordproc_v2.bin >> MULTIROM.BIN        # Wordproc v2              (11)