M48
; DRILL file {KiCad 8.0.2} date 2024-08-04T17:16:16+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-04T17:16:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X3.3837Y-2.0563
X3.3837Y-2.8437
X4.8797Y-2.0563
X4.8797Y-2.8437
M30
