M48
; DRILL file {KiCad (6.0.9)} date Wed Aug 16 20:18:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-16T20:18:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.2Y-1.5
X1.2Y-3.85
X4.15Y-1.5
X4.15Y-3.85
T0
M30
